export const VERSION = "1.0.0";
export const ARENA = { minX: -8.4, maxX: 8.4, ground: 0 };
export const ROUND_TIME = 99;

export const DIFFICULTY = {
  facil: { label: "Fácil", react: 0.42, block: 0.18, special: 0.22, err: 0.28, hp: 0.85, dmg: 0.8 },
  normal: { label: "Normal", react: 0.28, block: 0.32, special: 0.38, err: 0.16, hp: 1, dmg: 1 },
  dificil: { label: "Difícil", react: 0.16, block: 0.48, special: 0.52, err: 0.08, hp: 1.15, dmg: 1.12 },
  shinobi: { label: "Shinobi", react: 0.08, block: 0.62, special: 0.7, err: 0.03, hp: 1.3, dmg: 1.22 },
};

export const QUALITY = {
  baja: { shadows: false, bloom: false, buildings: 8, particles: 0.45 },
  media: { shadows: true, bloom: false, buildings: 14, particles: 0.75 },
  alta: { shadows: true, bloom: true, buildings: 22, particles: 1 },
};

export const VILLAGES = [
  { id: "leaf", name: "Hoja", symbol: "葉" },
  { id: "sand", name: "Arena", symbol: "砂" },
  { id: "mist", name: "Niebla", symbol: "霧" },
  { id: "cloud", name: "Nube", symbol: "雲" },
  { id: "stone", name: "Piedra", symbol: "石" },
  { id: "rain", name: "Lluvia", symbol: "雨" },
  { id: "sound", name: "Sonido", symbol: "音" },
  { id: "none", name: "Nómada", symbol: "忍" },
];

export const HAIR_STYLES = [
  { id: "spiky", name: "Pinchos clásicos" },
  { id: "messy", name: "Despeinado moderno" },
  { id: "longback", name: "Largo hacia atrás" },
  { id: "shortbob", name: "Bob con clips" },
  { id: "smooth", name: "Liso serpentino" },
  { id: "undercut", name: "Undercut urbano" },
  { id: "silver", name: "Mechón cubierto" },
  { id: "ponytail", name: "Coleta alta" },
  { id: "bun", name: "Moño de combate" },
  { id: "flow", name: "Cascada larga" },
  { id: "bowl", name: "Corte bowl" },
  { id: "wild", name: "Salvaje de arena" },
  { id: "twin", name: "Dobles colas" },
  { id: "buzz", name: "Rapeado táctico" },
  { id: "crown", name: "Corona de pinchos" },
];

export const EYE_STYLES = [
  { id: "normal", name: "Shinobi" },
  { id: "tomoe", name: "Tomoe escarlata" },
  { id: "pale", name: "Perla pálida" },
  { id: "slit", name: "Pupila de sabio" },
  { id: "ring", name: "Anillo violeta" },
  { id: "bar", name: "Marca de barra" },
  { id: "gold", name: "Ojo de bestia" },
];

export const MARKINGS = [
  { id: "none", name: "Ninguna" },
  { id: "whiskers", name: "Bigotes" },
  { id: "underEye", name: "Sombra inferior" },
  { id: "clan", name: "Abanico de clan" },
  { id: "scar", name: "Cicatriz" },
  { id: "dots", name: "Puntos Hyūga" },
  { id: "facepaint", name: "Pintura de guerra" },
  { id: "karma", name: "Sello interior" },
  { id: "sand", name: "Kanji de arena" },
];

export const OUTFITS = [
  { id: "hoodie", name: "Sudadera urbana" },
  { id: "flak", name: "Chaleco táctico" },
  { id: "cloak", name: "Capa de elite" },
  { id: "jacket", name: "Chaqueta corta" },
  { id: "crop", name: "Top de combate" },
  { id: "kimono", name: "Kimono moderno" },
  { id: "tactical", name: "Traje ANBU" },
];

export const ELEMENTS = {
  fire: {
    id: "fire",
    name: "Fuego",
    kana: "火",
    color: "#ff4d1a",
    special: {
      id: "goka",
      name: "Gran Bola de Fuego",
      type: "projectile",
      damage: 15,
      chakra: 24,
      cooldown: 1.15,
      speed: 11,
      size: 0.42,
      hitstun: 0.38,
    },
  },
  water: {
    id: "water",
    name: "Agua",
    kana: "水",
    color: "#3aa0ff",
    special: {
      id: "torrent",
      name: "Torrente Dragón",
      type: "projectile",
      damage: 13,
      chakra: 22,
      cooldown: 1.05,
      speed: 10,
      size: 0.5,
      hitstun: 0.42,
    },
  },
  lightning: {
    id: "lightning",
    name: "Rayo",
    kana: "雷",
    color: "#c9f6ff",
    special: {
      id: "chidori",
      name: "Perforación Relámpago",
      type: "dash",
      damage: 18,
      chakra: 28,
      cooldown: 1.4,
      speed: 16,
      hitstun: 0.5,
    },
  },
  wind: {
    id: "wind",
    name: "Viento",
    kana: "風",
    color: "#9cffb0",
    special: {
      id: "vacuum",
      name: "Hoja de Vacío",
      type: "projectile",
      damage: 12,
      chakra: 18,
      cooldown: 0.85,
      speed: 16,
      size: 0.28,
      hitstun: 0.28,
    },
  },
  earth: {
    id: "earth",
    name: "Tierra",
    kana: "土",
    color: "#c48a4a",
    special: {
      id: "spike",
      name: "Lanza de Roca",
      type: "trap",
      damage: 16,
      chakra: 26,
      cooldown: 1.35,
      hitstun: 0.55,
    },
  },
  ice: {
    id: "ice",
    name: "Hielo",
    kana: "氷",
    color: "#b8e7ff",
    special: {
      id: "mirror",
      name: "Aguja Helada",
      type: "projectile",
      damage: 11,
      chakra: 20,
      cooldown: 1.1,
      speed: 12,
      size: 0.3,
      hitstun: 0.6,
      freeze: 0.55,
    },
  },
  shadow: {
    id: "shadow",
    name: "Sombra",
    kana: "影",
    color: "#7a5cff",
    special: {
      id: "bind",
      name: "Atadura de Sombra",
      type: "bind",
      damage: 8,
      chakra: 26,
      cooldown: 1.6,
      hitstun: 0.9,
    },
  },
  sound: {
    id: "sound",
    name: "Sonido",
    kana: "音",
    color: "#e85cff",
    special: {
      id: "scream",
      name: "Grito Destructivo",
      type: "melee",
      damage: 14,
      chakra: 24,
      cooldown: 1.25,
      range: 2.4,
      hitstun: 0.7,
    },
  },
};

export const ELEMENT_IDS = Object.keys(ELEMENTS);

export function fusionUltimate(a, b) {
  const pair = [a, b].sort().join("+");
  const table = {
    "fire+lightning": { name: "Tormenta Ígnea", type: "dash", damage: 34, color: "#ff8a3a" },
    "fire+wind": { name: "Tifón Ardiente", type: "projectile", damage: 32, color: "#ff6a2a" },
    "fire+earth": { name: "Meteoro Shinobi", type: "trap", damage: 36, color: "#ff5520" },
    "fire+water": { name: "Vapor Asesino", type: "melee", damage: 30, color: "#ff9aa0" },
    "fire+ice": { name: "Cristal Magma", type: "projectile", damage: 31, color: "#ffb48a" },
    "fire+shadow": { name: "Amaterasu Falso", type: "bind", damage: 28, color: "#ff3344" },
    "fire+sound": { name: "Explosión Carmesí", type: "melee", damage: 33, color: "#ff3d7a" },
    "lightning+wind": { name: "Corte Tempestad", type: "dash", damage: 33, color: "#e8fff0" },
    "lightning+earth": { name: "Pilar Magnético", type: "trap", damage: 34, color: "#d0e8ff" },
    "lightning+water": { name: "Jaula Eléctrica", type: "bind", damage: 29, color: "#7ad7ff" },
    "lightning+ice": { name: "Lanza Aurora", type: "projectile", damage: 32, color: "#d9f6ff" },
    "lightning+shadow": { name: "Destello Vacío", type: "dash", damage: 35, color: "#b8a0ff" },
    "lightning+sound": { name: "Trueno Resonante", type: "melee", damage: 31, color: "#f0c8ff" },
    "wind+water": { name: "Torbellino Azul", type: "projectile", damage: 30, color: "#8af0ff" },
    "wind+earth": { name: "Vendaval de Polvo", type: "melee", damage: 29, color: "#d8c090" },
    "wind+ice": { name: "Cuchilla Polar", type: "projectile", damage: 31, color: "#e8ffff" },
    "wind+shadow": { name: "Corte Fantasma", type: "dash", damage: 32, color: "#c0ffd0" },
    "wind+sound": { name: "Silbido Mortal", type: "projectile", damage: 28, color: "#d0ffc8" },
    "earth+water": { name: "Prisión de Lodo", type: "bind", damage: 30, color: "#6aa0c8" },
    "earth+ice": { name: "Glaciar de Roca", type: "trap", damage: 35, color: "#c0d8e8" },
    "earth+shadow": { name: "Tumba Oscura", type: "trap", damage: 33, color: "#6a5a40" },
    "earth+sound": { name: "Sismo Aullante", type: "melee", damage: 34, color: "#c8a070" },
    "water+ice": { name: "Dragón Glacial", type: "projectile", damage: 34, color: "#9ad8ff" },
    "water+shadow": { name: "Niebla de Almas", type: "bind", damage: 27, color: "#6070c8" },
    "water+sound": { name: "Marea Estridente", type: "melee", damage: 30, color: "#80b0ff" },
    "ice+shadow": { name: "Espejo Negro", type: "bind", damage: 29, color: "#a0c0ff" },
    "ice+sound": { name: "Cristal Quebrado", type: "projectile", damage: 31, color: "#d0e0ff" },
    "shadow+sound": { name: "Concierto Umbrío", type: "melee", damage: 33, color: "#c090ff" },
  };
  const base = table[pair] || { name: "Jutsu Secreto", type: "melee", damage: 30, color: "#ffe08a" };
  return { ...base, chakra: 100, cooldown: 8, hitstun: 0.85, ultimate: true };
}

export const DEFAULT_APPEARANCE = {
  name: "Boruto-kei",
  gender: "androgynous",
  height: 1,
  skin: "#f0c7a0",
  faceShape: "sharp",
  eyeStyle: "normal",
  eyeColor: "#2a6adf",
  eyebrow: "sharp",
  markings: "whiskers",
  markingColor: "#3a2418",
  hairStyle: "messy",
  hairColor: "#f2d36b",
  hairAccent: "#2a2a2a",
  headband: true,
  village: "leaf",
  mask: "none",
  outfit: "hoodie",
  primaryColor: "#2b3548",
  secondaryColor: "#e8c36a",
  accentColor: "#3ee0ff",
  pants: "slim",
  shoes: "sneakers",
  cloak: false,
  earrings: true,
  gloves: false,
  goggles: false,
  scroll: true,
  elements: ["wind", "lightning"],
};

export const PRESETS = [
  {
    id: "uzumaki",
    name: "Uzumaki Rubio",
    desc: "Pinchos, bigotes y naranja de guerra",
    appearance: {
      name: "Naruto-kei",
      gender: "male",
      skin: "#f3c49a",
      hairStyle: "spiky",
      hairColor: "#f2d36b",
      eyeStyle: "normal",
      eyeColor: "#3a7a2a",
      markings: "whiskers",
      outfit: "jacket",
      primaryColor: "#e07020",
      secondaryColor: "#2a2a4a",
      accentColor: "#f2d36b",
      village: "leaf",
      headband: true,
      shoes: "sandals",
      elements: ["wind", "fire"],
      cloak: false,
    },
  },
  {
    id: "uchiha",
    name: "Uchiha Oscuro",
    desc: "Cabello largo, tomoe y azul noche",
    appearance: {
      name: "Sasuke-kei",
      gender: "male",
      skin: "#e8b894",
      hairStyle: "longback",
      hairColor: "#1a1a1e",
      eyeStyle: "tomoe",
      eyeColor: "#c81e3a",
      markings: "clan",
      outfit: "cloak",
      primaryColor: "#1c2430",
      secondaryColor: "#c81e3a",
      accentColor: "#e8c36a",
      village: "leaf",
      elements: ["fire", "lightning"],
      cloak: true,
    },
  },
  {
    id: "heir",
    name: "Heredero Moderno",
    desc: "Corte urbano, azul y marcas",
    appearance: {
      name: "Boruto-kei",
      gender: "male",
      skin: "#f0c7a0",
      hairStyle: "messy",
      hairColor: "#f2d36b",
      hairAccent: "#2a2a2a",
      eyeStyle: "bar",
      eyeColor: "#2a6adf",
      markings: "whiskers",
      outfit: "hoodie",
      primaryColor: "#2b3548",
      secondaryColor: "#3ee0ff",
      village: "leaf",
      shoes: "sneakers",
      elements: ["wind", "lightning"],
    },
  },
  {
    id: "scholar",
    name: "Estudiosa del Clan",
    desc: "Bob, gafas y tomoe",
    appearance: {
      name: "Sarada-kei",
      gender: "female",
      skin: "#eab392",
      hairStyle: "shortbob",
      hairColor: "#1a1a1e",
      eyeStyle: "tomoe",
      eyeColor: "#c81e3a",
      markings: "clan",
      outfit: "crop",
      primaryColor: "#c81e3a",
      secondaryColor: "#1c2430",
      goggles: true,
      village: "leaf",
      elements: ["fire", "earth"],
    },
  },
  {
    id: "snake",
    name: "Serpiente Pálida",
    desc: "Cabello liso, ojos de sabio",
    appearance: {
      name: "Mitsuki-kei",
      gender: "androgynous",
      skin: "#f6e0c8",
      hairStyle: "smooth",
      hairColor: "#d8e4ea",
      eyeStyle: "slit",
      eyeColor: "#6ad0a0",
      markings: "none",
      outfit: "kimono",
      primaryColor: "#d8e4ea",
      secondaryColor: "#3aa0a0",
      village: "leaf",
      headband: false,
      elements: ["wind", "lightning"],
    },
  },
  {
    id: "karma",
    name: "Marca Interior",
    desc: "Undercut, sello y negro",
    appearance: {
      name: "Kawaki-kei",
      gender: "male",
      skin: "#e0b090",
      hairStyle: "undercut",
      hairColor: "#2a2420",
      eyeStyle: "gold",
      eyeColor: "#c8a050",
      markings: "karma",
      markingColor: "#111",
      outfit: "hoodie",
      primaryColor: "#1a1a1e",
      secondaryColor: "#8a8a90",
      village: "none",
      headband: false,
      mask: "cyber",
      elements: ["earth", "fire"],
    },
  },
  {
    id: "pale-eyes",
    name: "Ojos Pálidos",
    desc: "Largo oscuro y perla",
    appearance: {
      name: "Hinata-kei",
      gender: "female",
      skin: "#f0c8b0",
      hairStyle: "flow",
      hairColor: "#1c1428",
      eyeStyle: "pale",
      eyeColor: "#dce8ff",
      markings: "dots",
      outfit: "jacket",
      primaryColor: "#3a2a58",
      secondaryColor: "#dce8ff",
      village: "leaf",
      elements: ["lightning", "shadow"],
    },
  },
  {
    id: "blossom",
    name: "Sakura de Guerra",
    desc: "Rosa corto y fuerza",
    appearance: {
      name: "Sakura-kei",
      gender: "female",
      skin: "#f3c2b0",
      hairStyle: "shortbob",
      hairColor: "#f2a0c0",
      eyeStyle: "normal",
      eyeColor: "#3a7a4a",
      markings: "none",
      outfit: "flak",
      primaryColor: "#e07090",
      secondaryColor: "#2a4030",
      village: "leaf",
      elements: ["earth", "water"],
    },
  },
  {
    id: "copy",
    name: "Copia Plateada",
    desc: "Mechón cubierto y rayo",
    appearance: {
      name: "Kakashi-kei",
      gender: "male",
      skin: "#e8b894",
      hairStyle: "silver",
      hairColor: "#c8d0d8",
      eyeStyle: "tomoe",
      eyeColor: "#c81e3a",
      mask: "lower",
      outfit: "flak",
      primaryColor: "#2a3848",
      secondaryColor: "#c8d0d8",
      village: "leaf",
      elements: ["lightning", "earth"],
    },
  },
  {
    id: "crow",
    name: "Cuervo Nocturno",
    desc: "Coleta, capa y tomoe",
    appearance: {
      name: "Itachi-kei",
      gender: "male",
      skin: "#e0b090",
      hairStyle: "ponytail",
      hairColor: "#141418",
      eyeStyle: "tomoe",
      eyeColor: "#c81e3a",
      markings: "clan",
      outfit: "cloak",
      cloak: true,
      primaryColor: "#1a1020",
      secondaryColor: "#c81e3a",
      village: "leaf",
      elements: ["fire", "shadow"],
    },
  },
  {
    id: "sand",
    name: "Arena Carmesí",
    desc: "Cabello salvaje y kanji",
    appearance: {
      name: "Gaara-kei",
      gender: "male",
      skin: "#f0c8a8",
      hairStyle: "wild",
      hairColor: "#c81e3a",
      eyeStyle: "ring",
      eyeColor: "#50c8a0",
      markings: "sand",
      outfit: "cloak",
      primaryColor: "#c8b090",
      secondaryColor: "#c81e3a",
      village: "sand",
      elements: ["earth", "wind"],
    },
  },
  {
    id: "fist",
    name: "Puño Verde",
    desc: "Bowl, cejas y taijutsu",
    appearance: {
      name: "Lee-kei",
      gender: "male",
      skin: "#e8b080",
      hairStyle: "bowl",
      hairColor: "#141414",
      eyebrow: "thick",
      eyeStyle: "normal",
      eyeColor: "#3a3a3a",
      outfit: "kimono",
      primaryColor: "#1e6b3a",
      secondaryColor: "#f2d36b",
      village: "leaf",
      elements: ["wind", "earth"],
    },
  },
  {
    id: "neji",
    name: "Hyūga Protector",
    desc: "Largo y perla",
    appearance: {
      name: "Neji-kei",
      gender: "male",
      skin: "#e8c0a0",
      hairStyle: "flow",
      hairColor: "#2a2018",
      eyeStyle: "pale",
      eyeColor: "#e8f0ff",
      markings: "dots",
      outfit: "jacket",
      primaryColor: "#d8c8a0",
      secondaryColor: "#3a2a18",
      village: "leaf",
      elements: ["lightning", "wind"],
    },
  },
  {
    id: "temari",
    name: "Abanico del Desierto",
    desc: "Coletas y viento",
    appearance: {
      name: "Temari-kei",
      gender: "female",
      skin: "#f0c8a0",
      hairStyle: "twin",
      hairColor: "#e8d080",
      eyeStyle: "normal",
      eyeColor: "#50a060",
      outfit: "crop",
      primaryColor: "#c8b060",
      secondaryColor: "#2a4030",
      village: "sand",
      elements: ["wind", "earth"],
    },
  },
  {
    id: "mist",
    name: "Espada de la Niebla",
    desc: "Vendaje y agua",
    appearance: {
      name: "Zabuza-kei",
      gender: "male",
      skin: "#d8b090",
      hairStyle: "flow",
      hairColor: "#1a1a1e",
      eyeStyle: "normal",
      eyeColor: "#3a3a48",
      mask: "lower",
      outfit: "tactical",
      primaryColor: "#1c2830",
      secondaryColor: "#4a7080",
      village: "mist",
      elements: ["water", "shadow"],
    },
  },
  {
    id: "cloud",
    name: "Nube Relámpago",
    desc: "Corte táctico y rayo",
    appearance: {
      name: "Darui-kei",
      gender: "male",
      skin: "#6a4a32",
      hairStyle: "undercut",
      hairColor: "#d8d0c0",
      eyeStyle: "normal",
      eyeColor: "#50a0d0",
      outfit: "flak",
      primaryColor: "#d8c848",
      secondaryColor: "#1c2430",
      village: "cloud",
      elements: ["lightning", "water"],
    },
  },
];

export const STAGES = [
  { id: "street", name: "Avenida Konoha-Neo", palette: ["#1b2230", "#c81e3a", "#3ee0ff"], rain: true },
  { id: "rooftop", name: "Azoteas de Hokage", palette: ["#12151c", "#e8c36a", "#ff6a2a"], rain: false },
  { id: "alley", name: "Callejón de Neón", palette: ["#0c0d14", "#e85cff", "#3ee0ff"], rain: true },
  { id: "station", name: "Andén Subterráneo", palette: ["#151820", "#3ee0ff", "#e8c36a"], rain: false },
  { id: "bridge", name: "Puente del Trueno", palette: ["#101820", "#c9f6ff", "#3aa0ff"], rain: true },
  { id: "plaza", name: "Plaza del Monumento", palette: ["#1a140e", "#e8c36a", "#c81e3a"], rain: false },
];

const ENEMY_NAMES = [
  "Genin Callejero", "Kunoichi de Distrito", "ANBU Renegado", "Chunin del Metro",
  "Asesino de Tejados", "Cazador de Scrolls", "Mercenario de Lluvia", "Espía de Sonido",
  "Jōnin Caído", "Guardia de Neón", "Bandido de Arena", "Ninja de Construcción",
  "Sicario del Puerto", "Hermana de Niebla", "Ronin Urbano", "Operativo Cloud",
  "Cazador de Bestias", "Médico Negro", "Doble de Clan", "Sello Roto",
  "Patrulla Nocturna", "Ladrón de Chakra", "Infiltrado", "Centinela",
];

const BOSSES = [
  {
    level: 5,
    name: "Akari Enra",
    title: "Llama del Distrito",
    portrait: "assets/img/boss-1.jpg",
    elements: ["fire", "earth"],
    appearance: {
      name: "Akari Enra",
      gender: "female",
      hairStyle: "wild",
      hairColor: "#c81e3a",
      eyeStyle: "gold",
      eyeColor: "#ff6a2a",
      markings: "facepaint",
      outfit: "jacket",
      primaryColor: "#1a1010",
      secondaryColor: "#ff4d1a",
      village: "leaf",
      elements: ["fire", "earth"],
    },
  },
  {
    level: 10,
    name: "Raijin Kuro",
    title: "Asesino de Neón",
    portrait: "assets/img/boss-2.jpg",
    elements: ["lightning", "shadow"],
    appearance: {
      name: "Raijin Kuro",
      gender: "male",
      hairStyle: "silver",
      hairColor: "#c8d0d8",
      eyeStyle: "bar",
      eyeColor: "#3ee0ff",
      mask: "cyber",
      outfit: "tactical",
      primaryColor: "#0c1018",
      secondaryColor: "#3ee0ff",
      village: "cloud",
      elements: ["lightning", "shadow"],
    },
  },
  {
    level: 15,
    name: "Yuki Shizuku",
    title: "Fantasma de Niebla",
    portrait: "assets/img/boss-3.jpg",
    elements: ["water", "ice"],
    appearance: {
      name: "Yuki Shizuku",
      gender: "female",
      hairStyle: "flow",
      hairColor: "#b8e7ff",
      eyeStyle: "pale",
      eyeColor: "#e8f8ff",
      outfit: "cloak",
      cloak: true,
      primaryColor: "#d8eef8",
      secondaryColor: "#3aa0ff",
      village: "mist",
      elements: ["water", "ice"],
    },
  },
  {
    level: 20,
    name: "Oto no Maō",
    title: "Señor del Sonido",
    portrait: "assets/img/boss-4.jpg",
    elements: ["sound", "wind"],
    appearance: {
      name: "Oto no Maō",
      gender: "male",
      hairStyle: "crown",
      hairColor: "#7a5cff",
      eyeStyle: "ring",
      eyeColor: "#e85cff",
      outfit: "tactical",
      primaryColor: "#1a1020",
      secondaryColor: "#e85cff",
      village: "sound",
      elements: ["sound", "wind"],
    },
  },
  {
    level: 25,
    name: "Kawa",
    title: "El Interior",
    portrait: "assets/img/boss-5.jpg",
    elements: ["earth", "lightning"],
    appearance: {
      name: "Kawa",
      gender: "male",
      hairStyle: "undercut",
      hairColor: "#2a2420",
      eyeStyle: "gold",
      markings: "karma",
      outfit: "hoodie",
      primaryColor: "#111",
      secondaryColor: "#8a8a90",
      mask: "cyber",
      village: "none",
      elements: ["earth", "lightning"],
    },
  },
  {
    level: 30,
    name: "Hokage Sombra",
    title: "El Último Hat",
    portrait: "assets/img/boss-6.jpg",
    elements: ["fire", "wind"],
    appearance: {
      name: "Hokage Sombra",
      gender: "male",
      hairStyle: "spiky",
      hairColor: "#f2d36b",
      eyeStyle: "tomoe",
      eyeColor: "#c81e3a",
      markings: "whiskers",
      outfit: "cloak",
      cloak: true,
      primaryColor: "#c81e3a",
      secondaryColor: "#e8c36a",
      village: "leaf",
      elements: ["fire", "wind"],
      height: 1.08,
    },
  },
];

function seeded(n) {
  const x = Math.sin(n * 999) * 10000;
  return x - Math.floor(x);
}

export function buildLevels() {
  const levels = [];
  for (let i = 1; i <= 30; i++) {
    const boss = BOSSES.find((b) => b.level === i);
    const stage = STAGES[(i - 1) % STAGES.length];
    if (boss) {
      levels.push({
        id: i,
        boss: true,
        name: boss.name,
        title: boss.title,
        portrait: boss.portrait,
        stage,
        enemy: {
          ...DEFAULT_APPEARANCE,
          ...boss.appearance,
          elements: boss.elements,
        },
        stats: {
          hp: 130 + i * 6,
          damage: 1.05 + i * 0.025,
          speed: 1.05,
          ai: "boss",
        },
      });
      continue;
    }
    const r = seeded(i);
    const r2 = seeded(i + 17);
    const preset = PRESETS[Math.floor(r * PRESETS.length)];
    const e1 = ELEMENT_IDS[Math.floor(seeded(i + 3) * ELEMENT_IDS.length)];
    let e2 = ELEMENT_IDS[Math.floor(seeded(i + 9) * ELEMENT_IDS.length)];
    if (e2 === e1) e2 = ELEMENT_IDS[(ELEMENT_IDS.indexOf(e1) + 1) % ELEMENT_IDS.length];
    levels.push({
      id: i,
      boss: false,
      name: ENEMY_NAMES[(i - 1) % ENEMY_NAMES.length],
      title: `Misión ${String(i).padStart(2, "0")}`,
      portrait: "assets/img/portrait-player.jpg",
      stage,
      enemy: {
        ...DEFAULT_APPEARANCE,
        ...preset.appearance,
        name: ENEMY_NAMES[(i - 1) % ENEMY_NAMES.length],
        hairColor: preset.appearance.hairColor,
        primaryColor: r > 0.5 ? "#1a2030" : preset.appearance.primaryColor,
        height: 0.94 + r2 * 0.12,
        elements: [e1, e2],
      },
      stats: {
        hp: 88 + i * 4,
        damage: 0.85 + i * 0.02,
        speed: 0.92 + i * 0.008,
        ai: "grunt",
      },
    });
  }
  return levels;
}

export const LEVELS = buildLevels();

export const DEFAULT_SETTINGS = {
  music: 0.55,
  sfx: 0.8,
  difficulty: "normal",
  quality: "alta",
  fullscreen: false,
  showHints: true,
  hitboxes: false,
};

export const DEFAULT_BINDS = {
  left: "KeyA",
  right: "KeyD",
  up: "KeyW",
  down: "KeyS",
  light: "KeyJ",
  heavy: "KeyK",
  kick: "KeyL",
  special1: "KeyU",
  special2: "KeyI",
  ultimate: "KeyO",
  block: "ShiftLeft",
  dash: "KeyP",
  pause: "Escape",
};

export const MOVES = {
  light: { startup: 0.1, active: 0.09, recovery: 0.16, damage: 6, hitstun: 0.28, blockstun: 0.14, knock: 1.6, range: 1.28, height: 1.15, chip: 1 },
  heavy: { startup: 0.2, active: 0.12, recovery: 0.28, damage: 11, hitstun: 0.4, blockstun: 0.2, knock: 2.6, range: 1.45, height: 1.2, chip: 2 },
  kick: { startup: 0.16, active: 0.12, recovery: 0.24, damage: 9, hitstun: 0.34, blockstun: 0.18, knock: 2.8, range: 1.55, height: 0.85, chip: 1.5 },
  crouchLight: { startup: 0.09, active: 0.08, recovery: 0.14, damage: 5, hitstun: 0.24, blockstun: 0.12, knock: 1.2, range: 1.15, height: 0.7, chip: 1 },
  airKick: { startup: 0.12, active: 0.16, recovery: 0.18, damage: 8, hitstun: 0.3, blockstun: 0.12, knock: 2.1, range: 1.35, height: 0.9, chip: 1 },
};
